### ISSUE TITLE
Pagine con warning

### ISSUE THREAD

**Issue by ThomasFuser** [ThomasFuser/Basic_Gym#1]
ciao bei, stavamo validando (io e @bosluca ) le pagine ed abbiamo notato che nella pagina "orari" ci sono una ottantina di warning (causa attributo headers). 

esempio:
`<td class="Martedì" headers="c2 pranzo_c"><span lang="en">Body Step</span></td>`

Crediamo siano dovuti al fatto che sia html5; la Gaggi gradisce l'html5?

**Comment by bosluca** [comment]
Io avrei risolto ma non so se è corretto secondo i criteri di accessibilità, il file non lo carico se qualcuno pensa di saper come risolverlo me lo dice e gli mando file con warning+file con modifiche fatte da me.
Se ci riuscissimo a trovare sarebbe meglio perché ci sono troppe modifiche che sono state fatte e non si capisce più quale sia la versione corretta/finale/che vada bene a tutti
